-- ================================================
-- COURSE CHALLENGES TABLE
-- Isolated system for course-specific coding challenges
-- ================================================

-- 1. Create course_challenges table
-- ID starts at 189000 as strictly requested
CREATE TABLE IF NOT EXISTS course_challenges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 189000 INCREMENT BY 1) PRIMARY KEY,
    course_id TEXT NOT NULL, -- KEEPING AS TEXT to match existing courses table
    topic_id TEXT NOT NULL,  -- KEEPING AS TEXT to match existing topics table
    topic_name VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    input_format TEXT,
    output_format TEXT,
    hints TEXT, -- Keeping as TEXT to allow simple storage (or JSON string)
    reference_output TEXT,
    language VARCHAR(50) DEFAULT 'C', -- Using VARCHAR instead of ENUM for flexibility, default 'C'
    difficulty VARCHAR(50) DEFAULT 'Easy',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create course_challenge_status table
-- Tracks user progress for these specific challenges
CREATE TABLE IF NOT EXISTS course_challenge_status (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_challenge_id INTEGER NOT NULL REFERENCES course_challenges(id) ON DELETE CASCADE,
    status VARCHAR(50) CHECK (status IN ('solved')), -- Simple enum simulation
    solved_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Ensure one entry per user per challenge
    CONSTRAINT unique_user_challenge UNIQUE (user_id, course_challenge_id)
);

-- 3. Indexes
CREATE INDEX IF NOT EXISTS idx_course_challenges_topic ON course_challenges(topic_id);
CREATE INDEX IF NOT EXISTS idx_course_challenges_course ON course_challenges(course_id);
CREATE INDEX IF NOT EXISTS idx_challenge_status_user ON course_challenge_status(user_id);

-- 4. Initial Seed Data (Test Challenge)
-- Only insert if empty to avoid duplicates on re-run
INSERT INTO course_challenges (course_id, topic_id, topic_name, title, description, input_format, output_format, hints, reference_output)
SELECT 'c-programming', 'c-syntax-rules', 'C Syntax Rules', 'Print Hello World', 'Write a program that prints "Hello, World!" to the console.', 'None', 'Hello, World!', 'Use printf function\nDon''t forget the newline character', 'Hello, World!'
WHERE NOT EXISTS (SELECT 1 FROM course_challenges WHERE id = 189000);
